# Generated by Django 4.0.4 on 2022-05-17 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpokenLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Mandarin', 'Mandarin'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Arabic', 'Arabic'), ('Bengali', 'Bengali'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Indonesian', 'Indonesian')], max_length=50, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spoken_languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
