# Generated by Django 4.0.4 on 2022-05-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_patients_first_name_alter_patients_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patients',
            unique_together={('doctor', 'email')},
        ),
    ]
